services:
  - type: web
    name: Sanyagoldreceiptsystem
    runtime: node
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm start
